(function () {
  if (typeof tinymce === 'undefined' || typeof tinymce.addI18n !== 'function') {
    return;
  }

  tinymce.addI18n('ja', {
    "Redo": "やり直し",
    "Undo": "元に戻す",
    "Cut": "切り取り",
    "Copy": "コピー",
    "Paste": "貼り付け",
    "Paste as text": "テキストとして貼り付け",
    "Select all": "すべて選択",
    "New document": "新しいドキュメント",
    "Ok": "OK",
    "Cancel": "キャンセル",
    "Close": "閉じる",
    "Visual aids": "ガイド",
    "Bold": "太字",
    "Italic": "斜体",
    "Underline": "下線",
    "Strikethrough": "取り消し線",
    "Superscript": "上付き",
    "Subscript": "下付き",
    "Clear formatting": "書式をクリア",
    "Remove": "削除",
    "Blocks": "ブロック",
    "Headings": "見出し",
    "Heading 1": "見出し 1",
    "Heading 2": "見出し 2",
    "Heading 3": "見出し 3",
    "Heading 4": "見出し 4",
    "Heading 5": "見出し 5",
    "Heading 6": "見出し 6",
    "Preformatted": "整形済みテキスト",
    "Paragraph": "段落",
    "Blockquote": "引用",
    "Div": "Div",
    "Inline": "インライン",
    "Address": "住所",
    "Text": "テキスト",
    "Font family": "フォント",
    "Font sizes": "フォントサイズ",
    "Default": "デフォルト",
    "Lower Alpha": "小文字アルファベット",
    "Lower Greek": "小文字ギリシャ文字",
    "Lower Roman": "小文字ローマ数字",
    "Upper Alpha": "大文字アルファベット",
    "Upper Roman": "大文字ローマ数字",
    "Alpha": "アルファベット",
    "Roman": "ローマ数字",
    "Numbered list": "番号付きリスト",
    "Bullet list": "箇条書き",
    "Square": "四角",
    "Circle": "丸",
    "Disc": "黒丸",
    "Increase indent": "インデントを増やす",
    "Decrease indent": "インデントを減らす",
    "Line height": "行の高さ",
    "Alignment": "配置",
    "Left": "左揃え",
    "Center": "中央揃え",
    "Right": "右揃え",
    "Justify": "均等割り付け",
    "None": "なし",
    "Resize": "サイズ変更",
    "Direction": "方向",
    "Left to right": "左から右",
    "Right to left": "右から左",
    "Insert/edit image": "画像の挿入/編集",
    "Alternative description": "代替テキスト",
    "Accessibility": "アクセシビリティ",
    "Image options": "画像オプション",
    "Source": "ソース",
    "Dimensions": "サイズ",
    "Constrain proportions": "縦横比を固定",
    "General": "一般",
    "Advanced": "詳細設定",
    "Style": "スタイル",
    "Border": "枠線",
    "Vertical space": "垂直余白",
    "Horizontal space": "水平余白",
    "Insert/edit media": "メディアの挿入/編集",
    "Insert/edit link": "リンクの挿入/編集",
    "Open link in...": "リンクを開く...",
    "Current window": "現在のウィンドウ",
    "None (no target)": "なし (ターゲットなし)",
    "New window": "新規ウィンドウ",
    "New window with status bar": "ステータスバー付き新規ウィンドウ",
    "Text to display": "表示するテキスト",
    "Url": "URL",
    "Title": "タイトル",
    "Link list": "リンク一覧",
    "Anchors": "アンカー",
    "Link": "リンク",
    "Insert link": "リンクを挿入",
    "Remove link": "リンクを削除",
    "Insert/edit anchor": "アンカーの挿入/編集",
    "Anchor": "アンカー",
    "Name": "名前",
    "Id": "ID",
    "Table": "表",
    "Insert table": "表を挿入",
    "Delete table": "表を削除",
    "Table properties": "表のプロパティ",
    "Row properties": "行のプロパティ",
    "Cell properties": "セルのプロパティ",
    "Merge cells": "セルの結合",
    "Split cell": "セルの分割",
    "Insert row before": "上に行を挿入",
    "Insert row after": "下に行を挿入",
    "Delete row": "行を削除",
    "Row": "行",
    "Insert column before": "左に列を挿入",
    "Insert column after": "右に列を挿入",
    "Delete column": "列を削除",
    "Column": "列",
    "Cols": "列数",
    "Rows": "行数",
    "Cell": "セル",
    "Cell type": "セルの種類",
    "Scope": "スコープ",
    "Header cell": "ヘッダーセル",
    "Row group": "行グループ",
    "Column group": "列グループ",
    "Row type": "行の種類",
    "Column type": "列の種類",
    "Header": "ヘッダー",
    "Body": "本体",
    "Footer": "フッター",
    "Border color": "枠線の色",
    "Background color": "背景色",
    "Show caption": "キャプションを表示",
    "Caption": "キャプション",
    "Width": "幅",
    "Height": "高さ",
    "Cell spacing": "セル間隔",
    "Cell padding": "セル内余白",
    "Responsive": "レスポンシブ",
    "Insert/edit video": "動画の挿入/編集",
    "Embed": "埋め込み",
    "Media poster (Image URL)": "ポスター画像 URL",
    "Remove media": "メディアを削除",
    "Fullscreen": "全画面表示",
    "Code view": "コード表示",
    "Insert/edit code sample": "コードサンプルの挿入/編集",
    "Language": "言語",
    "Insert/edit emoticon": "絵文字の挿入/編集",
    "Fullscreen control": "全画面コントロール",
    "Horizontal line": "水平線",
    "Insert/edit horizontal line": "水平線の挿入/編集",
    "Insert date/time": "日付/時刻の挿入",
    "Date/time": "日付/時刻",
    "Insert/edit special character": "特殊文字の挿入/編集",
    "Special character": "特殊文字",
    "Previous": "前へ",
    "Next": "次へ",
    "Find and replace": "検索と置換",
    "Find": "検索",
    "Replace with": "置換後の文字",
    "Replace": "置換",
    "Replace all": "すべて置換",
    "Find in selection": "選択範囲内を検索",
    "Match case": "大文字と小文字を区別",
    "Whole words": "完全一致",
    "Spellcheck": "スペルチェック",
    "Help": "ヘルプ",
    "Shortcuts": "ショートカット",
    "Formats": "書式",
    "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "ブラウザがクリップボードへの直接アクセスをサポートしていません。Ctrl+X/C/V を使用してください。",
    "Insert": "挿入",
    "Insert file": "ファイルを挿入",
    "Insert/edit file": "ファイルの挿入/編集",
    "Upload": "アップロード",
    "Browse for an image": "画像を参照",
    "Browse": "参照",
    "Emoticons": "絵文字",
    "Search": "検索",
    "No matches found": "一致するものが見つかりません",
    "Toolbar": "ツールバー",
    "More...": "さらに...",
    "Rich Text Area": "リッチテキストエリア",
    "Powered by {0}": "Powered by {0}",
    "Source code": "ソースコード",
    "Save": "保存",
    "Print": "印刷",
    "Preview": "プレビュー",
    "Select...": "選択...",
    "Yes": "はい",
    "No": "いいえ",
    "Paste column before": "左に列を貼り付け",
    "Paste column after": "右に列を貼り付け",
    "Paste row before": "上に行を貼り付け",
    "Paste row after": "下に行を貼り付け",
    "Cut column": "列を切り取り",
    "Copy column": "列をコピー",
    "Delete row group": "行グループを削除",
    "Delete column group": "列グループを削除",
    "Row group": "行グループ",
    "Column group": "列グループ",
    "Table styles": "表スタイル",
    "Cell styles": "セルスタイル",
    "Column header": "列ヘッダー",
    "Row header": "行ヘッダー",
    "Table caption": "表のキャプション",
    "Apply": "適用",
    "Update": "更新",
    "Insert/edit audio": "音声の挿入/編集",
    "Flip horizontally": "左右反転",
    "Flip vertically": "上下反転",
    "Rotate counterclockwise": "反時計回りに回転",
    "Rotate clockwise": "時計回りに回転",
    "Crop": "切り抜き",
    "Edit image": "画像を編集",
    "Image": "画像",
    "Rotate": "回転",
    "File": "ファイル",
    "Add": "追加",
    "Delete": "削除",
    "Are you sure you want to delete this table?": "この表を削除してもよろしいですか?",
    "Are you sure you want to delete this row?": "この行を削除してもよろしいですか?",
    "Are you sure you want to delete this column?": "この列を削除してもよろしいですか?",
    "Restore last draft": "最後の下書きを復元",
    "Insert template": "テンプレートを挿入",
    "Templates": "テンプレート",
    "Template": "テンプレート",
    "Color": "色",
    "Custom color": "カスタム色",
    "Custom...": "カスタム...",
    "No color": "色なし",
    "Remove color": "色を削除",
    "Background": "背景",
    "Background color": "背景色",
    "Text color": "文字色",
    "Show blocks": "ブロックを表示",
    "Show invisible characters": "不可視文字を表示",
    "Word count": "文字数",
    "Characters": "文字数",
    "Words": "単語数",
    "Characters (no spaces)": "文字数 (スペース除く)",
    "{0} words": "{0} 単語",
    "Document": "ドキュメント",
    "Anchor...": "アンカー...",
    "Insert/edit link...": "リンクの挿入/編集...",
    "Link...": "リンク...",
    "Media...": "メディア...",
    "Image...": "画像...",
    "Table...": "表...",
    "Restore last draft": "最後の下書きを復元",
    "Draft has been restored": "下書きを復元しました",
    "Special character...": "特殊文字...",
    "Source code...": "ソースコード...",
    "Fullscreen...": "全画面...",
    "Print...": "印刷...",
    "Find and replace...": "検索と置換...",
    "Paste as text...": "テキストとして貼り付け...",
    "Preferences": "設定",
    "Insert/edit iframe": "iframe の挿入/編集",
    "Border width": "枠線の幅",
    "Border style": "枠線のスタイル",
    "Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "ID は英字で始め、英数字・ハイフン・ドット・コロン・アンダースコアのみ使用できます。",
    "Name should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "名前は英字で始め、英数字・ハイフン・ドット・コロン・アンダースコアのみ使用できます。",
    "Row group": "行グループ",
    "Column group": "列グループ",
    "Role": "役割",
    "Cell spacing or padding may be inconsistent with HTML5.": "セルの間隔や余白は HTML5 では非推奨です。"
  });
})();
